### ISSUE TITLE
Prismaのマイグレーションに失敗する

### ISSUE THREAD

**Issue by uttk** [frouriojs/create-frourio-app#106]
## Description

`create-frourio-app`でひな型を作成して `yarn dev` を実行すると以下のエラーが発生し、Prisma のマイグレーションに失敗します。

```shell
yarn run v1.22.10
$ npm run migrate:up && run-p dev:*

> frourio-app-server@0.1.0 migrate:up /app/server
> prisma migrate up --create-db --experimental

Environment variables loaded from .env
Environment variables loaded from prisma/.env
Error: The current command "up" doesn't exist in the new version of Prisma Migrate.
Read more about how to upgrade: https://pris.ly/d/migrate-upgrade

                           ⋮
```

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [x] Linux ( Dockerの `centos:centos8` イメージを使用 )
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  `v12.18.4`
- **npm version:**
  `6.14.6`

## Additional context

多分、prismaのバージョンアップで従来のコマンドが使えなくなっている感じ？( 使ったこと無いので、よく分からない😥 )
prismaのgithubのreleaseを見ると、そんな感じがします。

**参考**

- [Release 2.13.0 · prisma/prisma](https://github.com/prisma/prisma/releases/tag/2.13.0)
- [Add Prisma Migrate to an existing project](https://www.prisma.io/docs/guides/prisma-guides/prisma-migrate-guides/add-prisma-migrate-to-a-project)

**Comment by solufa** [comment]
@uttk 
報告ありがとうございます！
出来るだけ早く修正リリースします

**Comment by solufa** [comment]
@uttk 

お待たせしました、修正をリリースしたので再度お試しください

Discordで技術サポートをしておりますのでfrourioを使ってみて困りごとがあればお気軽にご参加ください
https://discord.gg/SARkeDf

**Comment by uttk** [comment]
@solufa 

私の環境で確認したところ、無事実行できました。
迅速な対応ありがとうございました🙇‍♂️
