### ISSUE TITLE
Multiple database.json will be generated

### ISSUE THREAD

**Issue by HikaruEgashira** [frouriojs/create-frourio-app#108]
## Description

`.gitignore`では`database.json`が`{appname}/server/database.json`の位置にあることを期待してignoreされています。
しかし`yarn test`を行ったとき、DBのパスが相対パスのため、`{appname}/database.json`の位置にファイルが生成されます。

これにより、テスト時にのみ生成されるdatabase.jsonファイルはignoreされません。

`{appname}/server/database.json` is ignored by `.gitignore` but when execute `yarn test`,`{appname}/database.json` will be generated.
I want to ignroe `{appname}/database.json`.

## Environment

- **Package version:**
  
  `v0.20.0`
- **OS:**
  
  - [x] Linux
- **Node.js version:**
  
  `v14.15.1`
- **yarn version:**
  
  `1.22.10`

## Additional context

想定される解決策として`tasks.ts`の`dbPath`を絶対パスに書き換えるのがいいと思います。
No dbは実際に使うことはないと思いますが、気になったので報告しておきます。

**Comment by solufa** [comment]
@HikaruEgashira 

投稿ありがとうございました
v0.21.0 で絶対パスに変え、さらにテスト時には `database.json` を生成しないよう修正したのでお時間あるときにお試しください
