### ISSUE TITLE
サンプルの TODO アプリ(Next.js)で一覧取得APIが二重で呼ばれる

### ISSUE THREAD

**Issue by technote-space** [frouriojs/create-frourio-app#118]
## Description

バグと言うほどでもないですが、toggleDone などで更新された際にTaskの一覧取得APIが二回呼ばれるようです。

![スクリーンショット 2020-12-16 21 47 35](https://user-images.githubusercontent.com/39912269/102350606-80280100-3fe8-11eb-8d0e-7294913aa678.png)

![スクリーンショット 2020-12-16 21 47 43](https://user-images.githubusercontent.com/39912269/102350616-81f1c480-3fe8-11eb-9f0c-b6c15d0175a5.png)

## Environment

- **Package version:**
  
  `v0.21.4`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v12.20.0`
- **npm version:**
  
  `6.14.8`

## Additional context

server/templates/client/next/pages/index.tsx
```ts
const { data: tasks, error, mutate: setTasks } = useAspidaSWR(apiClient.tasks)
```

の mutate 

```ts
mutate: (data?: Data | Promise<Data> | mutateCallback<Data>, shouldRevalidate?: boolean) => Promise<Data | undefined>;
```

の shouldRevalidate に false を渡す、
```diff
- setTasks(await apiClient.tasks.$get())
+ setTasks(await apiClient.tasks.$get(), false)
```

または revalidate 

```ts
revalidate: () => Promise<boolean>;
```

 を使用する

```diff
- const { data: tasks, error, mutate: setTasks } = useAspidaSWR(apiClient.tasks)
+ const { data: tasks, error, revalidate } = useAspidaSWR(apiClient.tasks)

  // ...

- setTasks(await apiClient.tasks.$get())
+ revalidate()
```

のいずれかの変更で呼び出しは一回のみになりました。

**Comment by solufa** [comment]
@technote-space 

今回も投稿ありがとうございます
以前から薄っすら気になっていたので大変助かりました

revalidate方式を採用し修正リリースしたのでお時間あるときにご確認ください
