### ISSUE TITLE
フレームワーク選択部分をモジュール化する

### ISSUE THREAD

**Issue by su8ru** [frouriojs/create-frourio-app#152]
frouriojs/frourio.io#29 で使いたいのです

**Comment by solufa** [comment]
@LumaKernel 
特に期限ないので今やってる作業と調整しながら進めてもらえると嬉しいです

**Comment by LumaKernel** [comment]
cfa で見れる形式でなくとも、依存としてデータを取れるようにするのが良さそう。
やってみます。

**Comment by LumaKernel** [comment]
前回の解答を復元する? 部分、localStorage でやれば frourio.io でも対応できて、 `~/.frourio` を触る必要もなくなるかもしれない？（違う目的だったら教えて下さい）

（https://github.com/frouriojs/create-frourio-app/pull/146 はちょっと大きいのでこのあとで別でやると思います）

**Comment by solufa** [comment]
選択画面開くときのポートが毎回3000とは限らないからなあと思ってlocalStorageやめました
あとCUI実行のときも前回の回答を復元しているけど、このときlocalStorage使うのは難しいかなーと
CUIは復元なしにして、GUIの時はiframe仕込んでfrourio.ioのlocalStorageで管理しpostMessageで授受するのもありか？

**Comment by LumaKernel** [comment]
なるほど。そういうことなら、とりあえずそこはこのままでいいかもしれません。
