### ISSUE TITLE
TypeORM + webpack (minimize)

### ISSUE THREAD

**Issue by LumaKernel** [frouriojs/create-frourio-app#157]
`--mode production` のときに限ってエラーがでるのでなんでだろうとおもっていたんですが、TypeORM は クラス名などの情報を使っているのでマングリングされて違うテーブルとか探しに行ってしまうようでした。

https://github.com/typeorm/typeorm/blob/master/docs/faq.md#how-to-use-webpack-for-the-backend

簡単には minimize をオフる、もう少しやるなら uglify の必要な部分を設定して使う。
もしくはもう、 ts-node にしちゃうか。テンプレートとしてなにがいいか難しいですが…。
とりあえず https://github.com/frouriojs/create-frourio-app/pull/146 では minimize をオフって設定するようにしようとおもいます。

**Comment by solufa** [comment]
おお、気付かなかった・・・
TypeORM のときだけminimizeをオフにするのは良さそう
