### ISSUE TITLE
Add Context interface for global.$nuxt.$api

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#158]
## Description
https://github.com/frouriojs/create-frourio-app/blob/master/server/templates/client/nuxt/plugins/api.ts

Add Context for `$nuxt.$api`

```ts
declare module '@nuxt/types' {
  interface Context {
    $api: ApiInstance
  }
  interface NuxtAppOptions {
    $api: ApiInstance
  }
}
```

**Comment by LumaKernel** [comment]
このPR ( https://github.com/frouriojs/create-frourio-app/pull/146 ) からの差分だけ作ってみました。

https://github.com/LumaKernel/create-frourio-app/pull/2/files

**Comment by solufa** [comment]
おお、私が雑に型抽出した部分がまとまってる・・・
これ #146 にマージしてもらってOKですよ

**Comment by solufa** [comment]
#146 で解決
