### ISSUE TITLE
ディレクトリ名未入力時はCREATEボタンを不活性にする

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#160]
## Description

ディレクトリ名を入力しなくてもCREATE出来てしまう
カレントディレクトリに被さってインストールされるので割と大惨事・・・

## Describe the solution you'd like

未入力時は灰色にしてマウスホバーで説明を出すとか

**Comment by LumaKernel** [comment]
（これは同じ事故起こしました…）
どちらかというと、対象のディレクトリが、存在しないか、空である場合のみ作業をすすめる、としたほうがいいのかなと思っています。

**Comment by solufa** [comment]
ああー確かにディレクトリが空かどうかで判断する系のCLIツールあるね
Gitだったかな？
それでもOK

**Comment by LumaKernel** [comment]
空文字チェックは抜けてしまっていたのでそれの修正PRを作っておきます。
