### ISSUE TITLE
CREATE後の遷移を自動化

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#161]
## Description

CREATE後にアプリケーションの準備が出来ても見た目に変化がないので初見はどうすべきか迷う
インストール中にモーダルを閉じてOPENボタンを押しても画面真っ白なので準備完了するまでは「インストール中・・・」みたいな不活性ボタンにしたい

GUIのタブはそのままで、新しいタブで開くという点は踏襲して良さそう

## Describe the solution you'd like

旧実装では、GUIからポーリングしてアプリケーションのフロントとバックエンド両方から200が返ってきたら準備完了とみなしていた
ただ、localhostのポートが違うとNext.js以外はindex.htmlの取得でCORSのエラーになる
サーバーで200になるまでポーリングしてGUIに状況を返せばいいのかなあ

**Comment by LumaKernel** [comment]
開く部分に関しては、最初に CFA を開くのと同じ仕組みで cli 側から起動すればいい気がしてきた…
