### ISSUE TITLE
Sapper で型エラー

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#179]
## Description
Sapperで構築するとsrc/client.tsに型エラー
non-null-assertion で解決は出来る

```ts
import * as sapper from '@sapper/app';

sapper.start({
-	target: document.querySelector('#sapper')
+	target: document.querySelector('#sapper')!
});
```

typecheckで検知できてないのが辛いけど、今年中にSveltekitに移行しそうだから深追いしなくてもいいかあ

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by LumaKernel** [comment]
これクライアント側に対しても typecheck (svelte-checkとは別に) すれば取れそうです。
対処はうーん、assert 文いれようと思います。 Sapper の今後に合わせて create-frourio-app がどうしていくかというのもありそうですね…大変そう

**Comment by solufa** [comment]
Sapperはたまに更新されつつも終了が決まっているからねー
SvelteKitが正式リリースされたらSapperと置き換えたい
