### ISSUE TITLE
バイナリファイルのコピーミスでデータ破損

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#180]
## Description
server/service/generate.ts
69行目で全ファイルをUTF8で読んでるからwriteFileしているのでSapperのトップ画像が破損している

```ts
          const content = (await fs.promises.readFile(from)).toString('utf-8')
          const noEjs = isBinaryPath(p) && !p.endsWith('.snap')

          try {
            const output = noEjs
              ? content
              : ejs.render(content.replace(/\r/g, ''), templateContext)
            await fs.promises.writeFile(path.resolve(nowOut, p), output)
          } catch (e: unknown) {
            console.error(e)
            console.error(`Error occured while processing ${from}`)
            throw e
          }
```

`!p.endsWith('.snap')` のチェックは該当2ファイルだけだしなくてもいいような気がした
読み手に過剰に意図を推測させてしまう
何かエラーが出るなら必要な意図なのでOK、そこまでは試してない

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by LumaKernel** [comment]
`.snap` 特殊判定、前あったもの [`.filter((fp) => !isBinaryPath(fp) || path.extname(fp) === '.snap')`](https://github.com/LumaKernel/create-frourio-app/blob/225beef8/server/service/generate.ts#L25-L25) を残しておきましたが、現時点で .snap で EJS なものはなく、 v0.22 時点ぐらいで既になさそうでもあるので消しておきます！

**Comment by solufa** [comment]
私の消し忘れかあ・・・なぜその判定をしたのかもう覚えていない
