### ISSUE TITLE
アイコンをPOSTしても反映されない

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#181]
## Description
構築後の server/service/user.ts の37行目で API_DYNAMIC_DIR が空なので changeIcon が動作しない
```ts
  if (!iconsDir) {
    throw new Error('API_DYNAMIC_DIR is not configured.')
  }
```
API_DYNAMIC_DIR が環境変数としてセットされていない
サンプルコードの割に、API_DYNAMIC_DIR の役割がちょっとわかりづらいかも

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by LumaKernel** [comment]
おおすみません！これはスムーズに Lambda で使えるようにかんたんに変えられるようにしたものですが、どうなんだこれ…とか考えてたらデフォルト値入れ忘れてました…

分かりづらい…ですよね…とりあえずコメントですかね… .env.example のほうに書いてみます。もう少し書くと良さそうな場所ないか考えてみます

**Comment by solufa** [comment]
ああ、Lambda用の処理だったのか
そこまで考えが及ばなかったわ

**Comment by LumaKernel** [comment]
です、 Lambda はソースコードがある場所は read only なので、別途 EFS マウントするなどして `/efs-0/data/icons` とかにおいてもらうなどが必要になります、ということに気づいてここらへんを書き換えられるようにしました。

なんか DYNAMIC ってわかりにくいので UPLOAD にしたほうがいいような気がしてきました。
