### ISSUE TITLE
DBのデフォルトポート番号が合ってない

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#183]
## Description

GUIでMySQL/Postgresを変更したらDATABASE_PORTに3306/5432が入力されて欲しい
多分、初期値とユーザー入力を一緒に create-frourio-app.json に保存している気がする
元々はユーザー入力のみ保存していたのでデフォルトポートをDBごとに当てられた

ついでに、DB種別ごとにHOSTやPOSTなどのユーザー入力を保存しておきたい
元々の実装でもユーザーが一度5432と入力すると、MySQLでも5432になる
ローカル開発でもDBによってユーザー名など使い分けることに対応したい

JSONの形式が変わるのでcreate-frourio-app.jsonのverを3に上げて2からのマイグレーションも必要になる

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by LumaKernel** [comment]
近い形にもどしておきます。現行にした意味あんまりなかったです。そうなると ver も上げる必要もあんまりないですかね、新しいフィールドがたされるだけになって… ?（この今のバージョン入れた人はちょっと不整合起きますが）
