### ISSUE TITLE
インストール完了後の起動検知に失敗する

### ISSUE THREAD

**Issue by su8ru** [frouriojs/create-frourio-app#190]
## Description

インストール完了後、すでに起動できているのにも関わらず、起動検知に失敗する

![image](https://user-images.githubusercontent.com/33474143/109018416-719e4a00-76fb-11eb-8be4-5fa321dd1b1e.png)

## Environment

- **Package version:**
  
  `v0.26.3`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
  - [x] WSL 2 (Ubuntu 20.04.2 LTS on Windows 10 x86_64)
- **Node.js version:**
  
  `v14.14.0`
- **npm version:**
  
  `6.14.8`

## Additional context

- `8001` とある通り、裏でもう 1 つ cfa & frourio が動いています（関連性は不明）

**Comment by LumaKernel** [comment]
ありがとうございます。手動で開いたあと、タスク作成などはできる状態です？

**Comment by su8ru** [comment]
> ありがとうございます。手動で開いたあと、タスク作成などはできる状態です？

add / delete およびデータベースへの反映もできているので、問題なく動いていそうです。

**Comment by su8ru** [comment]
一度全部落として何も起動していない状態から試してみたのですが、なんの不具合もなく新規タブで `localhost:8000` が開きました！
ボタンも disabled が外れているので、正しく起動検知できていそうです…

![image](https://user-images.githubusercontent.com/33474143/109020877-b925d580-76fd-11eb-9dbc-9b8b15fb9217.png)

もしかしたら多重起動が原因の可能性も…？

**Comment by LumaKernel** [comment]
明日以降調査してみます…
多重起動は試してみましたが一応リリースされたもので試してみても問題なさそうでした。

実装した自分的には ① websocket で `ready` という文字を `/ws/ready` から受信して判定しているが、分割して送られているかもしれない (ストリーム/httpの仕様てきには分割されてもおかしくない？) ②dev 後、100秒間1秒間隔でポーリングしているがタイムアウトしている。

CLI 側で CFA を起動するのと同じように open すれば安定するんじゃないかというふうに思えてきたのでそういう再実装しようかと思っています。ただめちゃくちゃ起こるような状況がないかもう少ししらべてみます。

**Comment by solufa** [comment]
v0.27.1で解消したはずです！
