### ISSUE TITLE
CIでNext.jsのスナップショットテストが間に合わない

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#192]
## Description

templateのNext.jsのテストで、DOM更新を50ms待ってスナップショットを取る処理がある
https://github.com/frouriojs/create-frourio-app/blob/master/server/templates/%40testing%3Djest/%40client%3Dnext/test/pages/index.test.tsx#L46

ローカルでは問題ないが、GHAだと重くて更新が間に合わないことが10%程度の高確率で発生する
恐らくユーザーの環境でも同じことが発生するのでDOM更新を確実に検知する方法が知りたい

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by LumaKernel** [comment]
僕もGHAで観測しました。
ここはまさしく [`waitFor`](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor) ですね。

**Comment by LumaKernel** [comment]
私の書いたサンプルで変更した部分です、よければこれであとでPR 出します！ 
https://github.com/LumaKernel/frourio-sample-1/blob/e7a5bfa/test/pages/index.test.tsx#L57

```ts
await waitFor(() => expect(asFragment()).toMatchSnapshot())
```

**Comment by LumaKernel** [comment]
上記のwaitFor の中で 見えていることをテストする expect を書けばいいのかな、 assign してもらえればやっておきます

**Comment by solufa** [comment]
助かる、お願いします
