### ISSUE TITLE
テンプレートページを追加してpathpida導入

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#199]
## Description

pathpidaを組み込みたいけど、現状のページがどれも1つずつしかないので意味がない
Next.js/Nuxt.js/SvelteKitを複数ページに変えてpathpidaも導入する
（pathpidaをSapperに対応させる予定はなく、SvelteKitモードは開発中）

パス変数・クエリ・staticPathを活用して欲しい

**Comment by solufa** [comment]
pathpidaにSapperを追加したので対応お願いします
https://github.com/aspida/pathpida#setup---sapper
SvelteKitは見送り

**Comment by LumaKernel** [comment]
こちらは Next.js のみで一旦区切る。

https://github.com/frouriojs/create-frourio-app/issues/250
https://github.com/frouriojs/create-frourio-app/issues/249
