### ISSUE TITLE
GUI のホストが localhost ではない場合の対応

### ISSUE THREAD

**Issue by su8ru** [frouriojs/create-frourio-app#232]
## Description

GUI 起動画面の hostname が `localhost` ではない場合の対応を検討していただきたく……

WSL 2 では localhost が使えると謳われていますが、ときどき使えないことがあります。
その場合には local IPv4 を叩くのが一般的ですが、現状 `localhost:3000` を listen しているため GUI を開くことができません。

```
> lsof -i:3000
COMMAND   PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    25203 subaru   21u  IPv4 5598849      0t0  TCP localhost:3000 (LISTEN)
```

## Describe the solution you'd like

- `--port` と同じ要領で `--host` を通じて指定できるようにする
- `*:{port}` を listen するのもあり

`*:{port}` については、docusaurus v2 がそうです。

```
> lsof -i:3000
COMMAND   PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    25760 subaru   22u  IPv4 5599126      0t0  TCP *:3000 (LISTEN)
```

## Additional context

そもそも GUI を開けなかったときでも `localhost` 自体は生きていたので、なにか別の問題があるのかもしれません……（localhost forwarding の仕組みを知らず…）

**Comment by solufa** [comment]
@LumaKernel 
これ何か対処法思いつきますか・・・？

**Comment by hashue** [comment]
対応します！
