### ISSUE TITLE
[bug] Migrate options

### ISSUE THREAD

**Issue by toaru** [frouriojs/create-frourio-app#233]
## Description
When executing `"yarn migrate:dev --create-only"`
the option does not work and the migration is applied directly.

## Environment
- **Package version:**
0.28.0
- **OS:**
Linux
- **Node.js version:**
v14.15.4
- **yarn version:**
1.22.10

## Additional context
- In `"app_root/"`:  The behavior can be reproduced.
- In `"app_root/server/"`: The behavior can't be reproduced.

**Comment by IshinoJun** [comment]
@toaru 
Thanks for reporting the bug and creating the PR!
I'll contact you as soon as I finish reviewing.

**Comment by IshinoJun** [comment]
@solufa 
ルートのパッケージからサーバー側のスクリプトに対して、オプションを渡したいのであれば以下で実行可能ですね。
`yarn migrate:dev -- -- --create-only`

なので他と異なりこのコマンドだけ`ダブルダッシュ（--）`を加えるかは検討が必要です。
いくつかの対策案を考えてみました！

- `migrate:dev:createonly `っというコマンドを追加する
- ルートのパッケージからサーバー側のスクリプトを叩くコマンドには、ダブルダッシュ（--）を加える（オプションが指定可能なコマンド全てが対象）
- 上記のコマンド実行してもらうようドキュメントに追加する

`--create-only`は[手動でマイグレーションを変更したい際](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations)に利用するオプションなので、本番運用中であれば一定の利用する機会がありそうです！
[他のオプション](https://www.prisma.io/docs/reference/api-reference/command-reference)はぱっと見そこまで頻度は多くなさそうです。なのでこのオプションだけ、コマンドに追加するでもいいかなっと思ったりしました。

ご意見を伺いたいです！

---

To pass options from the root package to the server-side script, you can do the following

`yarn migrate:dev -- -- --create-only`

So, unlike other commands, we need to consider whether to add a `double dash (--)' to this command only.
I've considered a few possible solutions!

- Add the command `migrate:dev:createonly `.
- Add a double dash (--) to any command that strikes a server-side script from the root package (for all commands that can specify options)
- Add a description to the document to have it run the above command.

--create-only` is an option to use when you want to [change the migration manually](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/customizing-migrations), so it is likely to be used on certain occasions if you are in production!

[The other options](https://www.prisma.io/docs/reference/api-reference/command-reference) do not seem to be used that often.
so I thought it would be okay to add only this option to the command.

I would like to know you opinion on this issue.

**Comment by solufa** [comment]
@IshinoJun 
丁寧に調査していただきありがとうございます！
「migrate:dev:createonlyコマンドの追加」で対応しましょう

・使う機会が割とあるなら自明にコマンドがあると使いやすい
・ダブルダッシュをあちこちに残しておくのはスッキリしない
あたりが理由ですね

**Comment by solufa** [comment]
v0.28.2 で解決しました
