### ISSUE TITLE
`npm init frourio-app --answers`でGUIに遷移する

### ISSUE THREAD

**Issue by utamori** [frouriojs/create-frourio-app#236]
## Description

[Setup with CUI | frourio](https://frourio.io/docs/installation/cui)の例を試した際、
`npm init frourio-app --answers '{"dir":"my-project"}'`だけ、そのままプロジェクトが作成されず、GUIでのSetupに移行する

## Environment

- **Package version:**
  
  `v0.28.0`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v16.2.0`
- **npm version:**
  
  `7.13.0`

## Additional context

**Comment by IshinoJun** [comment]
@utamori 
バグ報告ありがとうございます！
調査・修正するのでお待ちください。

**Comment by hashue** [comment]
こちらnpmの仕様により、npm v7 以降は
`npm init frourio-app -- --answers '{"dir":"my-project"}'` と記述する必要があります。
参考リンク https://docs.npmjs.com/cli/v7/commands/npm-init#forwarding-additional-options

**Comment by utamori** [comment]
なるほどです！
