### ISSUE TITLE
GUI選択時にyarn/npmを賢くデフォルト選択してほしい

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#244]
## Description
たまたまプログラミング素人のインストールの様子を見ていて気付いたんだけど、yarnが初期選択されていると「npmに切り替える」ことに気付けないのでディレクトリ構築フェーズでyarnがなくて落ちる
![image](https://user-images.githubusercontent.com/9402912/126479393-87cb50d0-b639-468e-a7dc-1c58fbbb93c7.png)

GUI起動前にyarnがインストールされているか確認して初期選択値を変えられたらいいなと思った

**Comment by hashue** [comment]
これはデフォルトの選択値をnpmにしておけばいいような気がするのですが、いかがでしょう？

**Comment by solufa** [comment]
左をnpmにして、デフォルト選択にしてください、すみません

**Comment by LumaKernel** [comment]
resolved by https://github.com/frouriojs/create-frourio-app/pull/273
