### ISSUE TITLE
サーバーをesbuildに変更

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#251]
## Description
今Webpackで出来ている開発体験をesbuildでも再現できるかを調査する必要がある

**Comment by LumaKernel** [comment]
`npx esbuild server/endpoints/index.ts --bundle --platform=node --outfile=server/index.js`

などでできるかな？ [`--watch`](https://esbuild.github.io/api/#watch) をつければ watch モードにもなります。

一応例えば以下では成功しています。

https://github.com/LumaKernel/begin-frourio-next-app/blob/42f9ef8382c4001d63262a7e2032f761f5e678b8/package.json#L18

**Comment by IshinoJun** [comment]
@LumaKernel 
おぉ！素晴らしい！参考に私も手元で試してみます！

**Comment by IshinoJun** [comment]
@solufa @LumaKernel 
cfaで作成した環境をesbuildに変更してみました。
https://github.com/IshinoJun/esbuild-frourio-next-app/commit/1c7ec89196b07b96a5f68cee44b9e956b210c3d1

成功してそうです。見てもらえると！

**Comment by LumaKernel** [comment]
- `const root = process.cwd()` は `__dirname` ベースの方が cwd に依存せずに動くのでこちらのほうが良いかと思います
- esbuild v0.12.16 で追加された `--platform=node`  で `esbuild-node-externals` はほとんど必要なくなったと思いますが必要です？

**Comment by IshinoJun** [comment]
> esbuild v0.12.16 で追加された --platform=node で esbuild-node-externals はほとんど必要なくなったと思いますが必要です？

これ、`esbuild`に対応していない？パッケージ（`@prisma/client`、`fastify-jwt`、`fastify-static`）があって`production`だとビルド失敗するんですよねー。`external`に該当パッケージを指定するとした方がいいですかね？

**Comment by LumaKernel** [comment]
勘違いでした… esbuild-node-externals は引き続き必要そうです…！ありがとうございます、時間取らせてすみませんすみません

**Comment by IshinoJun** [comment]
@LumaKernel  @solufa 
コメントした構成で修正のPR作成してみますね！
