### ISSUE TITLE
prismaのseed機能

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#252]
## Description
https://www.prisma.io/docs/guides/database/seed-database
割とSeed使うのでデフォルトで入れられないかな

**Comment by IshinoJun** [comment]
@solufa 
手元で試した感じ、以下を行えばデフォルトで追加可能かと思います！

1. 適当なサンプルのseed.tsを用意する（taskとか）
2. seedコマンドを追加する

**Comment by solufa** [comment]
ありがとう！
いいプランですね、それで行きましょうー

**Comment by solufa** [comment]
マージ済み
