### ISSUE TITLE
自動生成ファイルが linter の ignore に追加されていない

### ISSUE THREAD

**Issue by su8ru** [frouriojs/create-frourio-app#338]
## Description

frouriojs/frourio#197 で `$*.ts` から `eslint-disable`, `prettier-ignore` が削除されているようですが、cfa のテンプレートの `.eslintignore`, `.prettierignore` によって ignore されていないため、create 直後に `yarn lint` を実行すると fail します。

もちろん「ignore せず linter 管理下に置く」パターンに対応できるのは重要ですが、殆どの場合は ignore するでしょうし、create 直後に lint が落ちるのはいただけません。

従って、テンプレートにおいては `.eslintignore`, `.prettierignore` によって自動生成ファイルを除外しておき、適宜ドキュメント等でアナウンスするといいのかなと思います（後者はわたしの仕事ですが）

## Environment

- **Package version:**
  
  `v0.32.2`
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v16.14.0`
- **npm version:**
  
  `8.3.1`

## Additional context

そういえば Aspida はこの変更の対象外なんでしょうか……？
Pathpida は変更されているようでしたが……

**Comment by LumaKernel** [comment]
ありがとうございます。ignoreファイルは対応します。
もとのissueは返信がなくて、他の方の温度感あまりわかっていないので、ignore挟み込むメリット・もともとの動機などがあれば追記していただけるとたすかります。

Aspidaは変更の対象です。一番最初に対応したつもりだったが、eslint-disableしかできていなかった。

**Comment by su8ru** [comment]
もともとの動機はわたしはわからないのですが、ignore ファイルのほうが融通が効いて望ましいという感じはします。

手元で ignore に追加して作業しているのですがまったく支障がないので、この方針で問題ないかと思います。
