### ISSUE TITLE
既存PJをcloneしてdevすると$server.tsが間に合わない

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#361]
## Description
あるPJで発生しただけで一般環境での検証はしてない

serverの`node ./scripts/build.dev.js`が`frourio --watch`より早いと$server.tsが無くてエラーになる

serverのnpm scriptsにpredevを追加するといいかも

```json
{
  "name": "frourio-app-server",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "predev": "npm run generate",
    "dev": "npm run migrate:dev && run-p dev:*"
```

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by LumaKernel** [comment]
`&&` にしようかな。依存をあまり増やしたくない。

それと、将来的にwireitを考えてはどうか、というのは考えられる。
notiosも専用のインテグレーションを作らなくても連携できるのではないかな？

**Comment by LumaKernel** [comment]
ちなみに私もこの問題には遭遇したことがあります。
