### ISSUE TITLE
fastify-* modulesのimportがエラーになる

### ISSUE THREAD

**Issue by IshinoJun** [frouriojs/create-frourio-app#362]
## Description

新規で作成すると、fastify-* modulesのimportが型ファイルがなくてエラーになる

<img width="537" alt="スクリーンショット 2022-05-06 20 15 40" src="https://user-images.githubusercontent.com/45793046/167121434-029eb99f-edf3-40a9-82a9-066ab702cd84.png">

`fastify-*` が非推奨になり、`@fastify/*` を利用する必要があるみたい
https://github.com/fastify/fastify/issues/3733

このせいでCFAのテストが落ちているかも

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by su8ru** [comment]
Frourio 本体の内部でも `fastify-*` をハードコードしている部分があるようなので、合わせて確認が必要そうですね。

https://github.com/frouriojs/frourio/issues/240
