### ISSUE TITLE
FastifyError: Failed building the validation schema for POST: /api/token, due to error headers schema is undefined

### ISSUE THREAD

**Issue by toco8** [frouriojs/create-frourio-app#413]
## Description

Fastifyの仕様変更により、`npx create-frourio-app`の実行に失敗するようになりました。
localhost:8000へアクセスすると、"`failed to load`"と表示されます。
Ubuntu 22.04, macOS Venturaの2環境で同様のエラーが発生することを確認しました。
`./server/node_modules/fastify/lib/route.js`の366行目をコメントアウトすることで暫定的に問題を回避しています。

## Environment

- **Package version:**
  `v0.36.0`
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  `v18.15.0`

- **npm version:**
  `9.6.2`

## Additional context

<details>
<summary>`npx create-frourio-app`実行ログ</summary>
<pre>
<code>$ npx create-frourio-app
open http://localhost:3000 in the browser
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /home/ubuntu/git/my-frourio-app/.git/

added 897 packages, and audited 898 packages in 2m

132 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 536 packages, and audited 537 packages in 30s

80 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

🎉  Successfully created project /home/ubuntu/git/my-frourio-app
  To get started:
        cd my-frourio-app
        npm run dev
  To build & start for production:      (start sqlite server yourself)
        cd my-frourio-app
        npm run build   npm run start

> frourio-app@0.1.0 generate
> run-p generate:*

> frourio-app@0.1.0 generate:pathpida
> pathpida --enableStatic

> frourio-app@0.1.0 generate:server
> npm run generate --prefix server

> frourio-app@0.1.0 generate:aspida
> aspida

server/api/$api.ts was built successfully.
/home/ubuntu/git/my-frourio-app/src/utils/$path.ts was built successfully.

> frourio-app-server@0.1.0 generate
> run-p generate:*

> frourio-app-server@0.1.0 generate:prisma
> prisma generate

> frourio-app-server@0.1.0 generate:frourio
> frourio

Environment variables loaded from .env
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 162ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
$server.ts was built successfully.

> frourio-app@0.1.0 lint:fix
> eslint --ext .ts,.js,.tsx . --fix && prettier --write "./**/*.{ts,js,tsx}"

/home/ubuntu/git/my-frourio-app/src/pages/article/index.tsx
  1:10  warning  'useCallback' is defined but never used  @typescript-eslint/no-unused-vars
  1:23  warning  'useState' is defined but never used     @typescript-eslint/no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

.eslintrc.js 92ms
aspida.config.js 16ms
ecosystem.config.js 13ms
jest.config.ts 247ms
server/api/article/_articleId@number/controller.ts 17ms
server/api/article/_articleId@number/index.ts 10ms
server/api/article/_articleId@number/validators.ts 21ms
server/api/article/controller.ts 14ms
server/api/article/index.ts 6ms
server/api/controller.ts 8ms
server/api/index.ts 7ms
server/api/tasks/_taskId@number/controller.ts 13ms
server/api/tasks/_taskId@number/index.ts 10ms
server/api/tasks/_taskId@number/validators.ts 10ms
server/api/tasks/controller.ts 16ms
server/api/tasks/index.ts 11ms
server/api/token/controller.ts 14ms
server/api/token/index.ts 5ms
server/api/user/controller.ts 14ms
server/api/user/hooks.ts 15ms
server/api/user/index.ts 8ms
server/entrypoints/index.ts 12ms
server/prisma/seed.ts 17ms
server/scripts/build.dev.js 12ms
server/scripts/build.prod.js 7ms
server/scripts/config.common.js 9ms
server/scripts/config.dev.js 7ms
server/scripts/config.prod.js 6ms
server/service/app.ts 13ms
server/service/article.ts 12ms
server/service/envValues.ts 10ms
server/service/tasks.ts 15ms
server/service/user.ts 13ms
server/test/server.test.ts 17ms
server/types/index.ts 4ms
src/components/Layout.tsx 18ms
src/components/UserBanner.tsx 41ms
src/pages/_app.tsx 22ms
src/pages/article/entry.tsx 14ms
src/pages/article/index.tsx 33ms
src/pages/index.tsx 39ms
src/utils/apiClient.ts 8ms
test/__mocks__/fileMock.js 4ms
test/pages/index.test.tsx 29ms
test/testUtils.tsx 7ms

> frourio-app@0.1.0 migrate:dev
> npm run migrate:dev --prefix server

> frourio-app-server@0.1.0 migrate:dev
> prisma migrate dev

Environment variables loaded from .env
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

Applying migration `20201209205045_`

The following migration(s) have been applied:

migrations/
  └─ 20201209205045_/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in
 118ms

prisma:warn The "ts-node" script in the package.json is not used anymore since version 3.0 and can now be removed.

> frourio-app@0.1.0 dev
> npm run migrate:dev && run-p dev:*

> frourio-app@0.1.0 migrate:dev
> npm run migrate:dev --prefix server

> frourio-app-server@0.1.0 migrate:dev
> prisma migrate dev

Environment variables loaded from .env
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

Already in sync, no schema change or pending migration was found.

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in
 110ms

> frourio-app@0.1.0 dev:client
> next dev -p 8000

> frourio-app@0.1.0 dev:aspida
> aspida --watch

> frourio-app@0.1.0 dev:server
> npm run dev --prefix server

> frourio-app@0.1.0 dev:pathpida
> pathpida --enableStatic --watch

> frourio-app-server@0.1.0 dev
> npm run generate && npm run migrate:dev && run-p dev:*

ready - started server on 0.0.0.0:8000, url: http://localhost:8000

> frourio-app-server@0.1.0 generate
> run-p generate:*

> frourio-app-server@0.1.0 generate:frourio
> frourio

> frourio-app-server@0.1.0 generate:prisma
> prisma generate

Environment variables loaded from .env
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 157ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

> frourio-app-server@0.1.0 migrate:dev
> prisma migrate dev

Environment variables loaded from .env
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

Already in sync, no schema change or pending migration was found.

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in
 98ms

> frourio-app-server@0.1.0 dev:build
> node ./scripts/build.dev.js

> frourio-app-server@0.1.0 dev:server
> node-dev --respawn index.js

> frourio-app-server@0.1.0 dev:frourio
> frourio --watch

> frourio-app-server@0.1.0 dev:prisma
> prisma generate --watch

[watch] build finished, watching for changes...
(node:4760) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[watch] build started (change: "api/tasks/_taskId@number/$relay.ts")
[watch] build finished
[INFO] 16:28:07 Restarting: /home/ubuntu/git/my-frourio-app/server/index.js has been modified
FastifyError: Failed building the validation schema for POST: /api/token, due to error headers schema is undefined
    at Boot.<anonymous> (/home/ubuntu/git/my-frourio-app/server/node_modules/fastify/lib/route.js:366:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at /home/ubuntu/git/my-frourio-app/server/node_modules/avvio/boot.js:160:12
    at /home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:275:7
    at done (/home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:200:5)
    at check (/home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
[ERROR] 16:28:07 FastifyError: Failed building the validation schema for POST: /api/token, due to error headers schema is undefined
Environment variables loaded from .env
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
(node:4811) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
FastifyError: Failed building the validation schema for POST: /api/token, due to error headers schema is undefined
    at Boot.<anonymous> (/home/ubuntu/git/my-frourio-app/server/node_modules/fastify/lib/route.js:366:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at /home/ubuntu/git/my-frourio-app/server/node_modules/avvio/boot.js:160:12
    at /home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:275:7
    at done (/home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:200:5)
    at check (/home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
[ERROR] 16:28:08 FastifyError: Failed building the validation schema for POST: /api/token, due to error headers schema is undefined
[INFO] 16:28:08 Restarting: /home/ubuntu/git/my-frourio-app/server/node_modules/.prisma/client/index.js has been modified
(node:4888) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Watching... /home/ubuntu/git/my-frourio-app/server/prisma/schema.prisma

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in
 149ms

FastifyError: Failed building the validation schema for POST: /api/token, due to error headers schema is undefined
    at Boot.<anonymous> (/home/ubuntu/git/my-frourio-app/server/node_modules/fastify/lib/route.js:366:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at /home/ubuntu/git/my-frourio-app/server/node_modules/avvio/boot.js:160:12
    at /home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:275:7
    at done (/home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:200:5)
    at check (/home/ubuntu/git/my-frourio-app/server/node_modules/avvio/plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
[ERROR] 16:28:09 FastifyError: Failed building the validation schema for POST: /api/token, due to error headers schema is undefined
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/ubuntu/git/my-frourio-app/.babelrc
event - compiled client and server successfully in 6.6s (200 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 134 ms (201 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling / (client and server)...
event - compiled client and server successfully in 1610 ms (316 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
</code>
</pre>
</details>

**Comment by solufa** [comment]
@toco8 
報告ありがとうございました
frourio@0.32.0 / create-frourio-app@0.37.0
で修正完了しました
