### ISSUE TITLE
[feature] next での SPA export script の追加

### ISSUE THREAD

**Issue by su8ru** [frouriojs/create-frourio-app#42]
`export` とかで `run-s build:front && next export` すればよさそう…？

**Comment by solufa** [comment]
@su8ru 

https://nextjs.org/docs/advanced-features/static-html-export
これですね

インストール時にstaticかどうか質問して `build: "next build && next export"` にするか、質問無しで`export: "~~"` にするか6月に悩んでいたまま実装を忘れていました

すっかり忘れていたので助かりました、ありがとうございます
もう少し考えさせてください

**Comment by su8ru** [comment]
Next だと SPA / SSR で実装が変わってしまうのが悩ましい……

Nuxt 選択時の挙動と統一するのなら前者が望ましい気もしますが、ややこしいことになりそうなので、後者で十分な気も…？

**Comment by solufa** [comment]
@su8ru 

「SPA / SSR で実装が変わってしまう」という情報も踏まえて両方を試してみた結果、前者のbuildに統一するようにしてみました
v0.11.1リリース済みです

- インストール時にNext.jsを選択するとビルドモードをBasic/Staticから選ぶ
- Basic/Staticで同じコードになるようgetInitialPropsを削除して代わりにuseAspidaSWRを使用
- 最新のcreate-next-appの初期状態に合わせてCSSの記述方法を変更

React Hooksの知見がなくてSWR＋POST/PATCHの併用が適切か自信がありません
（POST/PATCH以降のGETの結果が変わるのにSWRを使っていいのかというあたり）

ちょっと触ってみて違和感あれば教えてもらえると助かります

**Comment by su8ru** [comment]
おおお、ありがとうございます

まず思ったのは、`mutate` を使わないと SWR が管理してるキャッシュが更新されないような気がします どうなんでしょう(?)
（私自身 SWR は全然使ったこと無いのでもっと自信が無いですが…）

```diff
-  const { data, error } = useAspidaSWR(apiClient.tasks)
+  const { data: tasks, error, mutate: setTasks } = useAspidaSWR(apiClient.tasks)
   const [label, setLabel] = useState('')
-  const [tasks, setTasks] = useState(data)
```

```diff
-  if (!data) return <div>loading...</div>
+  if (!tasks) return <div>loading...</div>
-  if (!tasks) {
-    setTasks(data)
-    return <div>loading...</div>
-  }
```

そして、これ Prettier が怒っています… (`"singleQuote": true`)

```ts
import useAspidaSWR from "@aspida/swr"
```

**Comment by solufa** [comment]
非常に的確な修正でした、ありがとうございます！
いただいたコードをそのまま取り入れてv0.11.2をリリースしました
Prettier の件全く気付かなかったし、mutateの使い方も勉強になりました
